# Generated by Django 3.2.12 on 2022-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.FloatField(default=0),
        ),
    ]
