# Generated by Django 3.2.12 on 2022-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
