# Generated by Django 3.2.12 on 2022-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
