# Generated by Django 3.2.12 on 2022-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_wishlist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
