# Generated by Django 3.2.12 on 2022-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
