# Generated by Django 3.2.12 on 2022-02-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_wishlist_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping',
        ),
    ]
