# Generated by Django 3.2.12 on 2022-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220218_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='shipping',
        ),
    ]
