# Generated by Django 3.2.12 on 2022-02-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_categories_subcategories_subsubcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subsubcategories',
            old_name='sub_sub_category',
            new_name='sub_subcategory',
        ),
        migrations.RenameField(
            model_name='subsubcategories',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
