# Generated by Django 3.2.12 on 2022-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondaryImage1',
            field=models.ImageField(null=True, upload_to='secondaryImages'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondaryImage2',
            field=models.ImageField(null=True, upload_to='secondaryImages'),
        ),
    ]
