# Generated by Django 3.2.12 on 2022-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_image_product_primaryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(max_length=1, null=True, upload_to='images'),
        ),
    ]
