# Generated by Django 3.2.12 on 2022-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_primaryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondaryImage1',
            field=models.ImageField(null=True, upload_to='secondaryImages'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondaryImage2',
            field=models.ImageField(null=True, upload_to='secondaryImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
