# Generated by Django 3.2.12 on 2022-02-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20220225_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primaryImage',
            new_name='primary_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='secondaryImage1',
            new_name='secondary_image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='secondaryImage2',
            new_name='secondary_image2',
        ),
    ]
