# Generated by Django 3.2.12 on 2022-02-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20220225_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubSubCategories',
            new_name='MoreCategories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='morecategories',
            old_name='sub_subcategory',
            new_name='more_categories',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='subcategory',
            new_name='subcategories',
        ),
    ]
