# Generated by Django 3.2.12 on 2022-02-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20220226_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='morecategories',
            old_name='more_categories',
            new_name='more_category',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='subcategories',
            new_name='subcategory',
        ),
    ]
