# Generated by Django 3.2.12 on 2022-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20220227_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(null=True, upload_to='categoryImages'),
        ),
    ]
