# Generated by Django 3.2.12 on 2022-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_subcategories_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image1', models.ImageField(upload_to='sliderImages')),
                ('slider_image2', models.ImageField(upload_to='sliderImages')),
                ('slider_image3', models.ImageField(upload_to='sliderImages')),
            ],
        ),
    ]
