# Generated by Django 3.2.12 on 2022-02-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_sliderimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimages',
            old_name='slider_image1',
            new_name='slider_image',
        ),
        migrations.RemoveField(
            model_name='sliderimages',
            name='slider_image2',
        ),
        migrations.RemoveField(
            model_name='sliderimages',
            name='slider_image3',
        ),
    ]
