# Generated by Django 3.2.12 on 2022-02-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20220228_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.morecategories'),
        ),
    ]
