# Generated by Django 3.2.12 on 2022-03-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20220302_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategories'),
        ),
    ]
