# Generated by Django 3.2.12 on 2022-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_brand_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cash_on_delivery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='home_delivery',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
