# Generated by Django 3.2.12 on 2022-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20220307_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_warranty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
